<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ForeverPin.Domain\ForeverPin.Domain.csproj" />
        <ProjectReference Include="..\ForeverPin.Persistence\ForeverPin.Persistence.csproj" />
    </ItemGroup>

</Project>
