<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.*" />
        <PackageReference Include="Stripe.net" Version="52.0.0" />
        <PackageReference Include="WoW2.Sdk.Backend.Beta" Version="10.0.45-beta" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ForeverPin.Application\ForeverPin.Application.csproj" />
        <ProjectReference Include="..\ForeverPin.Domain\ForeverPin.Domain.csproj" />
        <ProjectReference Include="..\ForeverPin.Persistence\ForeverPin.Persistence.csproj" />
    </ItemGroup>

</Project>
